apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      volumes:
        - name: redis-config
          configMap:
            name: redis-cm
        - name: redis-certificates
          secret:
            secretName: redis-crt
            defaultMode: 256
      containers:
      - name: master
        image: redis:6.2-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_TLS_CERT_FILE
          value: /etc/ssl/certs/redis.crt 
        - name: REDIS_TLS_KEY_FILE
          value:  /etc/ssl/certs/redis.key
        - name: REDIS_TLS_CA_FILE
          value: /etc/ssl/certs/redis.crt
        volumeMounts:
          - name: redis-config
            mountPath: /usr/local/etc/redis/redis-tls.conf
            subPath: redis-tls.conf
          - name: redis-certificates
            mountPath: /etc/ssl/certs
            readOnly: true
